export default [
  { type: 'text', author: `giuliandrimba`, id: 0, data: { text: `Why don't they have salsa on the table?` }, upvotes: 0 },
  { type: 'text', author: `mattmezza`, id: 1, data: { text: `What do you need salsa for?` }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 2, data: { text: `Salsa is now the number one condiment in America.` }, upvotes: 0 },
  { type: 'text', author: `mattmezza`, id: 3, data: { text: `You know why? Because people like to say 'salsa.' 'Excuse me, do you have salsa?' 'We need more salsa.' 'Where is the salsa? No salsa?'` }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 4, data: { text: `You know it must be impossible for a Spanish person to order seltzer and not get salsa. 'I wanted seltzer, not salsa.'` }, upvotes: 0 },
  { type: 'text', author: `mattmezza`, id: 5, data: { text: `Don't you know the difference between seltzer and salsa?? You have the seltezer after the salsa!` }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 6, data: { text: `See, this should be a show. This is the show. ` }, upvotes: 0 },
  { type: 'text', author: `mattmezza`, id: 7, data: { text: `What?` }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 8, data: { text: `This. Just talking.` }, upvotes: 0 },
  { type: 'text', author: `mattmezza`, id: 9, data: { text: `Yeah, right.` }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 10, data: { text: `I'm really serious. I think that's a good idea. ` }, upvotes: 0 },
  { type: 'text', author: `mattmezza`, id: 11, data: { text: `Just talking? Well what's the show about?` }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 12, data: { text: `It's about nothing.` }, upvotes: 0 },
  { type: 'text', author: `mattmezza`, id: 100, data: { text: `No story?` }, upvotes: 0 },
  { type: 'system', id: 13, data: { text: 'You have been transferred to another operator', meta: '04-07-2018 15:57' }, upvotes: 0 },
  { type: 'text', author: `support`, id: 16, data: { text: `You've got to have a story. You've got to have a story. You've got to have a story. You've got to have a story. You've got to have a story. You've got to have a story. ` }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 18, data: { text: `Do you read me...`, meta: '✓✓ Read' }, upvotes: 0 },
  { type: 'text', author: `giuliandrimba`, id: 19, data: { text: `...or not?`, meta: '✓ Delivered' }, upvotes: 0 },
  { type: 'system', id: 20, data: { text: 'User changed security key', meta: '04-08-2018 15:57' }, upvotes: 0 },
  { type: 'text', author: `support`, id: 21, data: { text: `What about suggestions?` }, reply: 20, upvotes: 0 }
]
